export const sampleScenarioNames = [
  'qualified_sold',
  'returned_approved',
  'unsold_no_buyer',
  'rejected_low_quality',
  'duplicate_capture',
  'suppressed_opt_out',
  'nurtured_unsold',
  'nurtured_rejected',
] as const;

export const roleExperienceRoles = [
  {
    name: 'Homeowner Lead Submitter',
    currentSurface: 'Synthetic Formbricks webhook sample data and admin lead timeline.',
    evidence: 'Webhook-created lead id, persisted lead status, consent-safe local-only data.',
  },
  {
    name: 'Agentic Workflow Worker',
    currentSurface: 'Hatchet-backed lifecycle transitions surfaced through admin workflow APIs.',
    evidence: 'Captured, enriched, qualified/rejected, auctioned, sold/unsold/nurtured events.',
  },
  {
    name: 'Buyer / Contractor',
    currentSurface: 'Local buyer listener, buyer roster, wallet, return, and daily-report APIs.',
    evidence: 'Active funded buyer, delivery/report fields, return-request state, wallet balances.',
  },
  {
    name: 'Operator / Admin',
    currentSurface: 'Unauthenticated local /admin control surface for technical proofing.',
    evidence: 'Timeline review controls, buyer controls, KPIs, readiness, and screenshots.',
  },
  {
    name: 'Business Owner',
    currentSurface: 'Readiness, KPI, buyer coverage, wallet coverage, and evidence manifests.',
    evidence: 'Technical local readiness passes while commercial paid launch remains blocked.',
  },
] as const;

export const roleExperienceWorkflow = {
  name: 'Role Experience Agentic Workflow',
  slug: 'role-experience-agentic-workflow',
  objective:
    'Verify each StormLead role can be tested with local synthetic sample data before true role-specific UI/auth ships.',
  appPath: '/admin',
  inputs: [
    'Running ping-post FastAPI app at STORMLEAD_ADMIN_URL or http://127.0.0.1:8003',
    'Real local database with current migrations applied',
    'Synthetic V1 sample scenarios generated by scripts/simulate_v1_leads.py',
    'No real homeowner, buyer, ad platform, payment, SMS, email, or public webhook contact',
  ],
  outputs: [
    'testing/runs/<timestamp>-role-experience-agentic-workflow/plan.md',
    'testing/runs/<timestamp>-role-experience-agentic-workflow/evidence.json',
    'testing/runs/<timestamp>-role-experience-agentic-workflow/logs/cowork-log.md',
    'testing/runs/<timestamp>-role-experience-agentic-workflow/logs/assertions.json',
    'testing/runs/<timestamp>-role-experience-agentic-workflow/reviews/review.md',
    'testing/runs/<timestamp>-role-experience-agentic-workflow/screenshots/',
  ],
  analysis: [
    'Current StormLead role proof is local and persona-based because buyer/homeowner portals and auth are intentionally deferred.',
    'Sample data must come from real local workflow scripts and persisted audit rows, not Playwright route mocks.',
    'Codex App browser is useful for preview, but official proof remains headed Playwright/Cowork artifacts.',
  ],
  plan: [
    { key: 'operator', label: 'Open the local operator/admin control surface' },
    { key: 'homeowner', label: 'Verify synthetic homeowner lead sample data is visible' },
    { key: 'agent', label: 'Verify agentic lifecycle events are persisted in the timeline' },
    { key: 'buyer', label: 'Verify buyer/contractor roster and daily-report evidence' },
    { key: 'review', label: 'Exercise operator hold and approve review controls' },
    { key: 'business', label: 'Verify business-owner readiness and commercial launch lock' },
    { key: 'evidence', label: 'Save role screenshots, logs, assertions, and review notes' },
  ],
  reviewNotes: [
    'Current role proof uses test personas over local APIs and the unauthenticated admin page.',
    'Future phase: add homeowner intake UI, buyer portal, role-gated operator auth, and business-owner reporting.',
    'Future phase default: local dev role switcher first, real auth only after current proof is stable.',
  ],
} as const;

export type RoleExperienceWorkflow = typeof roleExperienceWorkflow;
