"""stormlead shared core: models, events, filter dsl, observability."""

from stormlead_core.dedup import (
    DuplicateWindow,
    QualityScore,
    build_duplicate_window,
    initial_quality_score,
    normalize_address,
    normalize_phone,
)
from stormlead_core.env_gate import (
    ProductionSafetyError,
    assert_production_safe,
    hostname_resolves_to_global_addresses,
    is_approved_external_webhook_url,
    is_local_webhook_url,
    is_production,
)
from stormlead_core.events import (
    CallEvent,
    LeadCaptured,
    LeadEvent,
    PingPostResult,
    StormDetected,
    StormEvent,
)
from stormlead_core.filters import BuyerFilter, evaluate_filter
from stormlead_core.logging import configure_logging, get_logger
from stormlead_core.models import (
    Buyer,
    BuyerSalesStage,
    BuyerStatus,
    DamageTier,
    Lead,
    LeadClass,
    LeadSource,
    LeadStatus,
    Storm,
    StormSeverity,
)
from stormlead_core.object_storage import (
    InvalidObjectKeyError,
    LocalFilesystemObjectStorage,
    ObjectNotFoundError,
    ObjectStorageError,
    StoredObject,
    local_object_storage_from_env,
)
from stormlead_core.observability import (
    ERROR_SINK,
    bind_correlation_id,
    correlation_scope,
    current_correlation_id,
    emit_event,
    emit_metric,
)
from stormlead_core.pipeline import (
    InvalidPipelineTransitionError,
    PipelineState,
    assert_transition,
    can_transition,
    is_terminal,
    next_states,
)
from stormlead_core.provider_safety import (
    ProviderArea,
    ProviderDecision,
    provider_decision,
    provider_kill_switch_change_plan,
    provider_live_approved,
    provider_pause_snapshot,
    provider_paused,
    provider_url_allowed,
)
from stormlead_core.replay import ReplayPlan, build_replay_plan

__all__ = [
    "ERROR_SINK",
    "Buyer",
    "BuyerFilter",
    "BuyerSalesStage",
    "BuyerStatus",
    "CallEvent",
    "DamageTier",
    "DuplicateWindow",
    "InvalidObjectKeyError",
    "InvalidPipelineTransitionError",
    "Lead",
    "LeadCaptured",
    "LeadClass",
    "LeadEvent",
    "LeadSource",
    "LeadStatus",
    "LocalFilesystemObjectStorage",
    "ObjectNotFoundError",
    "ObjectStorageError",
    "PingPostResult",
    "PipelineState",
    "ProductionSafetyError",
    "ProviderArea",
    "ProviderDecision",
    "QualityScore",
    "ReplayPlan",
    "StoredObject",
    "Storm",
    "StormDetected",
    "StormEvent",
    "StormSeverity",
    "assert_production_safe",
    "assert_transition",
    "bind_correlation_id",
    "build_duplicate_window",
    "build_replay_plan",
    "can_transition",
    "configure_logging",
    "correlation_scope",
    "current_correlation_id",
    "emit_event",
    "emit_metric",
    "evaluate_filter",
    "get_logger",
    "hostname_resolves_to_global_addresses",
    "initial_quality_score",
    "is_approved_external_webhook_url",
    "is_local_webhook_url",
    "is_production",
    "is_terminal",
    "local_object_storage_from_env",
    "next_states",
    "normalize_address",
    "normalize_phone",
    "provider_decision",
    "provider_kill_switch_change_plan",
    "provider_live_approved",
    "provider_pause_snapshot",
    "provider_paused",
    "provider_url_allowed",
]
